const presentesPorNome  = {
"Andre Murano": "Pijama nerd (G)",
"Akira" :"Boxer azul-marinho (G) + mimo a sua escolha",
"Aline":"Fio dental de renda vinho M + mimo a sua escolha",
"Amanda":"Conjunto verde esmeralda com alcinhas finas (sutiã P/42 + calcinha P/M)",
"Aninha":"Camisola branca com toque romântico (tamanho P)",
"Bia (Minas)":"Camisola preta com toque romântico (tamanho P)",
"Bianca":"Fio dental azul marinho M + mimo a sua escolha",
"Bibi":"Conjunto preto (sutiã P/42 + calcinha P/M)",
"Bruna":"Pijama de calor P",
"Bruno":"Short de dormir liso em preto ou azul-marinho (G)",
"Carol":"Conjunto de renda vermelho (sutiã P/42 + calcinha M)",
"Caetano":"Pijama de calor G (para o noivo)",
"Dani Gogoni":"Camisola de cetim vinho com renda (tamanho P)",
"Diego":"Boxer azul (G) + mimo a sua escolha",
"Du Nishi":"Boxer cinza (G) + mimo a sua escolha",
"Dudu":"Presente livre, presenteie com o que você quiser",
"Fabiana":"Dadinho do amor (ações e partes do corpo) + mimo a sua escolha",
"Fernando Nishi":"Avental de churrasco “sensual” ou com corpo musculoso desenhado (G)",
"Fernando":"Samba cançao  + mimo a sua escolha",
"Flávio":"Pijama longo de algodão em cinza, azul ou preto (G)",
"Guilherme":"Cueca Boxer de sexy shop – tamanho G + mimo a sua escolha",
"Gustavo":"Boxer marrom (G)  + mimo a sua escolha",
"Heloísa":"Tanga preta M + mimo a sua escolha",
"Jaque Cris":"Calcinha rosa com lacinho discreto + mimo a sua escolha",
"Jaqueline":"Fio dental de renda vinho M + mimo a sua escolha",
"Jaqueline de Paulo":"Calcinha estilo “hot pant” preta M + mimo a sua escolha",
"Jessica":"Tanga verde escuro com lacinho discreto + mimo a sua escolha",
"Joana":"Fio dental bege com detalhe em tule M + mimo a sua escolha",
"João":"Samba cançao  + mimo a sua escolha",
"Jun":"Copo ou caneca personalizada com memes ou piadas internas",
"Laura":"Camisola de cetim P",
"Lauren":"Conjunto rosé (sutiã P/42 + calcinha P/M)",
"Léo Hassato":"Lubrificante de sabor + mimo a sua escolha",
"Leo Nakamura":"Boxer grafite (G)  + mimo a sua escolha",
"Léo Nishi":"Vibrador BIG GIANT (para o noivo)",
"Letícia":"Pijama leve em rosé ou azul-marinho (tamanho P)",
"Lucas Alves":"Samba cançao  + mimo a sua escolha",
"Lucas Troibicz":"Camiseta básica para dormir em preto, branca ou cinza (G) (para o noivo)",
"Lucia":"Conjunto preto em tule com transparência (sutiã P/42 + calcinha P/M)",
"Mateus":"Boxer verde (G)  + mimo a sua escolha",
"Mauricio":"Boxer grafite (G)  + mimo a sua escolha",
"Meg":"Camisola preta com renda P",
"Mika":"Calcinha estilo “hot pant” branca M + mimo a sua escolha",
"Miriely":"Conjunto preto (sutiã P/42 + calcinha M)",
"Murilo":"Camisinha que brilha no escuro + mimo a sua escolha (para o noivo)",
"Natalia":"Robe de cetim P",
"Nic Nishimura":"Top bojo removivel rendado tamanho P",
"Nicole Almeida":"Tanga rosé em microfibra M + mimo a sua escolha",
"Nino":"Boxer azul (G)  + mimo a sua escolha",
"Paula":"Pijama leve (tamanho P)",
"Rafael Lemes":"Copo ou caneca personalizada com memes ou piadas internas",
"Rafael Sperling":"Boxer vinho (G)  + mimo a sua escolha",
"Rapha":"Avental de churrasco “sensual” ou com corpo musculoso desenhado (G)",
"Regina":"Fio dental de renda vinho M + mimo a sua escolha",
"Thaís":"Calcinha estilo “hot pant” preta M + mimo a sua escolha",
"Thiago Kamida":"Pijama inverno + mimo a sua escolha (para o noivo)",
"Tici":"Pijama longo de inverno cinza ou bege (tamanho P)",
"Valkiria":"Conjunto preto em tule com transparência (sutiã P/42 + calcinha P/M)",
"Vanessa":"Tanga verde escuro com lacinho discreto + mimo a sua escolha",
"Willians":"Boxer preta (G) + Boxer branca (G)"

  };
  